name: aeclms
description: Community loan management & tracking system
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.10.7 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Backend
  supabase_flutter: ^2.16.0

  # State management
  flutter_riverpod: ^3.4.2

  # Routing
  go_router: ^17.3.0

  # UI / theme
  google_fonts: ^8.2.0
  flutter_svg: ^2.3.0
  cached_network_image: ^3.4.1

  # Forms & validation
  reactive_forms: ^18.2.2

  # Files / documents (for uploading loan forms, IDs, etc.)
  image_picker: ^1.2.3

  # Utilities
  intl: ^0.20.2
  equatable: ^2.1.0
  url_launcher: ^6.3.2
  file_picker: ^11.0.3
  pdf: ^3.13.0
  printing: ^5.15.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  flutter_local_notifications: ^22.2.0
  flutter_launcher_icons: ^0.14.4
  local_notifier: ^0.1.6
  open_file: ^4.0.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.15.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/loading_animation/
    - assets/animations/splash_animation/
    - assets/app_icon.png
    - assets/icon/icon.png
    - assets/icon.png
  # fonts:
  #   - family:
  #     fonts:
  #       - asset:
  #       - asset:
  #         style:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

  web:
    generate: false

  macos:
    generate: false

  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256   

dependency_overrides:
  meta: 1.18.0