// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRyLwN0X4IRWJik_jC565yN7hFIfyy2rQ',
    appId: '1:30193772972:web:49d58674a6ee0ddb7db209',
    messagingSenderId: '30193772972',
    projectId: 'aeclms-5c6fc',
    authDomain: 'aeclms-5c6fc.firebaseapp.com',
    storageBucket: 'aeclms-5c6fc.firebasestorage.app',
    measurementId: 'G-BJX4DSCTX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5wV1QsE0zc9IKWWyJ3a3Kyrw25APLPNA',
    appId: '1:30193772972:android:1cbd3c85ca144b087db209',
    messagingSenderId: '30193772972',
    projectId: 'aeclms-5c6fc',
    storageBucket: 'aeclms-5c6fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwdl90VyKWPXYB7aeFk9wfgTYEa19n3Ko',
    appId: '1:30193772972:ios:72d489d64a4831fe7db209',
    messagingSenderId: '30193772972',
    projectId: 'aeclms-5c6fc',
    storageBucket: 'aeclms-5c6fc.firebasestorage.app',
    iosBundleId: 'com.example.aeclms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwdl90VyKWPXYB7aeFk9wfgTYEa19n3Ko',
    appId: '1:30193772972:ios:72d489d64a4831fe7db209',
    messagingSenderId: '30193772972',
    projectId: 'aeclms-5c6fc',
    storageBucket: 'aeclms-5c6fc.firebasestorage.app',
    iosBundleId: 'com.example.aeclms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRyLwN0X4IRWJik_jC565yN7hFIfyy2rQ',
    appId: '1:30193772972:web:f4e3a603539d1ca87db209',
    messagingSenderId: '30193772972',
    projectId: 'aeclms-5c6fc',
    authDomain: 'aeclms-5c6fc.firebaseapp.com',
    storageBucket: 'aeclms-5c6fc.firebasestorage.app',
    measurementId: 'G-DKWZBEC4HP',
  );
}
